//
//  File.swift
//  FlagQuiz
//
//  Created by 이수한 on 2018. 3. 18..
//  Copyright © 2018년 이수한. All rights reserved.
//

import Foundation

struct FlagInfo {
    var name: String
    var fullName: String
    var imageName: String
}

let flagInfo = [
    FlagInfo(name: "아프가니스탄", fullName: "Afghanistan", imageName: "Afghanistan.png"),
    FlagInfo(name: "알바니아", fullName: "Albania", imageName: "Albania.png"),
    FlagInfo(name: "알제리", fullName: "Algeria", imageName: "Algeria.png"),
    FlagInfo(name: "안도라", fullName: "Andorra", imageName: "Andorra.png"),
    FlagInfo(name: "앙골라", fullName: "Angola", imageName: "Angola.png"),
    FlagInfo(name: "앤티가 바부 다", fullName: "Antigua and Barbuda", imageName: "Antigua_and_Barbuda.png"),
    FlagInfo(name: "아르헨티나", fullName: "Argentina", imageName: "Argentina.png"),
    FlagInfo(name: "아르메니아", fullName: "Armenia", imageName: "Armenia.png"),
    FlagInfo(name: "호주", fullName: "Australia", imageName: "Australia.png"),
    FlagInfo(name: "오스트리아", fullName: "Austria", imageName: "Austria.png"),
    FlagInfo(name: "아제르바이잔", fullName: "Azerbaijan", imageName: "Azerbaijan.png"),
    FlagInfo(name: "바레인", fullName: "Bahrain", imageName: "Bahrain.png"),
    FlagInfo(name: "방글라데시", fullName: "Bangladesh", imageName: "Bangladesh.png"),
    FlagInfo(name: "바베이도스", fullName: "Barbados", imageName: "Barbados.png"),
    FlagInfo(name: "벨라루스", fullName: "Belarus", imageName: "Belarus.png"),
    FlagInfo(name: "벨기에", fullName: "Belgium", imageName: "Belgium.png"),
    FlagInfo(name: "벨리즈", fullName: "Belize", imageName: "Belize.png"),
    FlagInfo(name: "베냉", fullName: "Benin", imageName: "Benin.png"),
    FlagInfo(name: "부탄", fullName: "Bhutan", imageName: "Bhutan.png"),
    FlagInfo(name: "볼리비아", fullName: "Bolivia", imageName: "Bolivia.png"),
    FlagInfo(name: "보스니아 헤르체고비나", fullName: "Bosnia and Herzegovina", imageName: "Bosnia_and_Herzegovina.png"),
    FlagInfo(name: "보츠와나", fullName: "Botswana", imageName: "Botswana.png"),
    FlagInfo(name: "브라질", fullName: "Brazil", imageName: "Brazil.png"),
    FlagInfo(name: "브루나이", fullName: "Brunei", imageName: "Brunei.png"),
    FlagInfo(name: "불가리아", fullName: "Bulgaria", imageName: "Bulgaria.png"),
    FlagInfo(name: "부키 나 파소", fullName: "Burkina Faso", imageName: "Burkina_Faso.png"),
    FlagInfo(name: "캄보디아", fullName: "Cambodia", imageName: "Cambodia.png"),
    FlagInfo(name: "카메룬", fullName: "Cameroon", imageName: "Cameroon.png"),
    FlagInfo(name: "캐나다", fullName: "Canada", imageName: "Canada.png"),
    FlagInfo(name: "카보 베르데", fullName: "Cape Verde", imageName: "Cape_Verde.png"),
    FlagInfo(name: "칠레", fullName: "Chile", imageName: "Chile.png"),
    FlagInfo(name: "콜롬비아", fullName: "Colombia", imageName: "Colombia.png"),
    FlagInfo(name: "코스타리카", fullName: "Costa Rica", imageName: "Costa_Rica.png"),
    FlagInfo(name: "크로아티아", fullName: "Croatia", imageName: "Croatia.png"),
    FlagInfo(name: "쿠바", fullName: "Cuba", imageName: "Cuba.png"),
    FlagInfo(name: "키프로스", fullName: "Cyprus", imageName: "Cyprus.png"),
    FlagInfo(name: "덴마크", fullName: "Denmark", imageName: "Denmark.png"),
    FlagInfo(name: "지부티", fullName: "Djibouti", imageName: "Djibouti.png"),
    FlagInfo(name: "도미니카", fullName: "Dominica", imageName: "Dominica.png"),
    FlagInfo(name: "동 티모르", fullName: "East Timor", imageName: "East_Timor.png"),
    FlagInfo(name: "에콰도르", fullName: "Ecuador", imageName: "Ecuador.png"),
    FlagInfo(name: "이집트", fullName: "Egypt", imageName: "Egypt.png"),
    FlagInfo(name: "엘살바도르", fullName: "El Salvador", imageName: "El_Salvador.png"),
    FlagInfo(name: "에리트레아", fullName: "Eritrea", imageName: "Eritrea.png"),
    FlagInfo(name: "에스토니아", fullName: "Estonia", imageName: "Estonia.png"),
    FlagInfo(name: "에티오피아", fullName: "Ethiopia", imageName: "Ethiopia.png"),
    FlagInfo(name: "피지", fullName: "Fiji", imageName: "Fiji.png"),
    FlagInfo(name: "핀란드", fullName: "Finland", imageName: "Finland.png"),
    FlagInfo(name: "부룬디", fullName: "Burundi", imageName: "Burundi.png"),
    FlagInfo(name: "차드", fullName: "Chad", imageName: "Chad.png"),
    FlagInfo(name: "코트 디부 아르", fullName: "Côte d'Ivoire", imageName: "Côte_d'Ivoire.png"),
    FlagInfo(name: "적도 기니", fullName: "Equatorial Guinea", imageName: "Equatorial_Guinea.png"),
    FlagInfo(name: "모리셔스", fullName: "Mauritius", imageName: "Mauritius.png"),
    FlagInfo(name: "모잠비크", fullName: "Mozambique", imageName: "Mozambique.png"),
    FlagInfo(name: "남 수단", fullName: "South Sudan", imageName: "South_Sudan.png"),
    FlagInfo(name: "수단", fullName: "Sudan", imageName: "Sudan.png"),
    FlagInfo(name: "아랍 에미레이트", fullName: "the United Arab Emirates", imageName: "the_United_Arab_Emirates.png"),
    FlagInfo(name: "프랑스", fullName: "France", imageName: "France.png"),
    FlagInfo(name: "가봉", fullName: "Gabon", imageName: "Gabon.png"),
    FlagInfo(name: "그루지야", fullName: "Georgia", imageName: "Georgia.png"),
    FlagInfo(name: "독일", fullName: "Germany", imageName: "Germany.png"),
    FlagInfo(name: "가나", fullName: "Ghana", imageName: "Ghana.png"),
    FlagInfo(name: "그리스", fullName: "Greece", imageName: "Greece.png"),
    FlagInfo(name: "그레나다", fullName: "Grenada", imageName: "Grenada.png"),
    FlagInfo(name: "과테말라", fullName: "Guatemala", imageName: "Guatemala.png"),
    FlagInfo(name: "기니 비사우", fullName: "Guinea-Bissau", imageName: "Guinea-Bissau.png"),
    FlagInfo(name: "기니", fullName: "Guinea", imageName: "Guinea.png"),
    FlagInfo(name: "가이아나", fullName: "Guyana", imageName: "Guyana.png"),
    FlagInfo(name: "아이티", fullName: "Haiti", imageName: "Haiti.png"),
    FlagInfo(name: "온두라스", fullName: "Honduras", imageName: "Honduras.png"),
    FlagInfo(name: "헝가리", fullName: "Hungary", imageName: "Hungary.png"),
    FlagInfo(name: "아이슬란드", fullName: "Iceland", imageName: "Iceland.png"),
    FlagInfo(name: "인도", fullName: "India", imageName: "India.png"),
    FlagInfo(name: "인도네시아 공화국", fullName: "Indonesia", imageName: "Indonesia.png"),
    FlagInfo(name: "이란", fullName: "Iran", imageName: "Iran.png"),
    FlagInfo(name: "이라크", fullName: "Iraq", imageName: "Iraq.png"),
    FlagInfo(name: "아일랜드", fullName: "Ireland", imageName: "Ireland.png"),
    FlagInfo(name: "이스라엘", fullName: "Israel", imageName: "Israel.png"),
    FlagInfo(name: "이탈리아", fullName: "Italy", imageName: "Italy.png"),
    FlagInfo(name: "자메이카", fullName: "Jamaica", imageName: "Jamaica.png"),
    FlagInfo(name: "일본", fullName: "Japan", imageName: "Japan.png"),
    FlagInfo(name: "요르단", fullName: "Jordan", imageName: "Jordan.png"),
    FlagInfo(name: "카자흐스탄", fullName: "Kazakhstan", imageName: "Kazakhstan.png"),
    FlagInfo(name: "케냐", fullName: "Kenya", imageName: "Kenya.png"),
    FlagInfo(name: "키리바시", fullName: "Kiribati", imageName: "Kiribati.png"),
    FlagInfo(name: "코소보", fullName: "Kosovo", imageName: "Kosovo.png"),
    FlagInfo(name: "쿠웨이트", fullName: "Kuwait", imageName: "Kuwait.png"),
    FlagInfo(name: "키르기스스탄", fullName: "Kyrgyzstan", imageName: "Kyrgyzstan.png"),
    FlagInfo(name: "라오스", fullName: "Laos", imageName: "Laos.png"),
    FlagInfo(name: "라트비아", fullName: "Latvia", imageName: "Latvia.png"),
    FlagInfo(name: "레바논", fullName: "Lebanon", imageName: "Lebanon.png"),
    FlagInfo(name: "레소토", fullName: "Lesotho", imageName: "Lesotho.png"),
    FlagInfo(name: "라이베리아", fullName: "Liberia", imageName: "Liberia.png"),
    FlagInfo(name: "리비아", fullName: "Libya", imageName: "Libya.png"),
    FlagInfo(name: "리히텐슈타인", fullName: "Liechtenstein", imageName: "Liechtenstein.png"),
    FlagInfo(name: "리투아니아", fullName: "Lithuania", imageName: "Lithuania.png"),
    FlagInfo(name: "룩셈부르크", fullName: "Luxembourg", imageName: "Luxembourg.png"),
    FlagInfo(name: "마케도니아", fullName: "Macedonia", imageName: "Macedonia.png"),
    FlagInfo(name: "마다가스카르", fullName: "Madagascar", imageName: "Madagascar.png"),
    FlagInfo(name: "말라위", fullName: "Malawi", imageName: "Malawi.png"),
    FlagInfo(name: "말레이시아", fullName: "Malaysia", imageName: "Malaysia.png"),
    FlagInfo(name: "몰디브", fullName: "Maldives", imageName: "Maldives.png"),
    FlagInfo(name: "말리", fullName: "Mali", imageName: "Mali.png"),
    FlagInfo(name: "몰타", fullName: "Malta", imageName: "Malta.png"),
    FlagInfo(name: "모리타니", fullName: "Mauritania", imageName: "Mauritania.png"),
    FlagInfo(name: "멕시코", fullName: "Mexico", imageName: "Mexico.png"),
    FlagInfo(name: "몰도바", fullName: "Moldova", imageName: "Moldova.png"),
    FlagInfo(name: "모나코", fullName: "Monaco", imageName: "Monaco.png"),
    FlagInfo(name: "몽골리아", fullName: "Mongolia", imageName: "Mongolia.png"),
    FlagInfo(name: "몬테네그로", fullName: "Montenegro", imageName: "Montenegro.png"),
    FlagInfo(name: "모로코", fullName: "Morocco", imageName: "Morocco.png"),
    FlagInfo(name: "미얀마", fullName: "Myanmar", imageName: "Myanmar.png"),
    FlagInfo(name: "나미비아", fullName: "Namibia", imageName: "Namibia.png"),
    FlagInfo(name: "나우루", fullName: "Nauru", imageName: "Nauru.png"),
    FlagInfo(name: "뉴질랜드", fullName: "New Zealand", imageName: "New_Zealand.png"),
    FlagInfo(name: "니카라과", fullName: "Nicaragua", imageName: "Nicaragua.png"),
    FlagInfo(name: "니제르", fullName: "Niger", imageName: "Niger.png"),
    FlagInfo(name: "나이지리아", fullName: "Nigeria", imageName: "Nigeria.png"),
    FlagInfo(name: "북한", fullName: "North Korea", imageName: "North_Korea.png"),
    FlagInfo(name: "노르웨이", fullName: "Norway", imageName: "Norway.png"),
    FlagInfo(name: "오만", fullName: "Oman", imageName: "Oman.png"),
    FlagInfo(name: "파키스탄", fullName: "Pakistan", imageName: "Pakistan.png"),
    FlagInfo(name: "팔라우", fullName: "Palau", imageName: "Palau.png"),
    FlagInfo(name: "팔레스타인", fullName: "Palestine", imageName: "Palestine.png"),
    FlagInfo(name: "파나마", fullName: "Panama", imageName: "Panama.png"),
    FlagInfo(name: "파푸아 뉴기니", fullName: "Papua New Guinea", imageName: "Papua_New_Guinea.png"),
    FlagInfo(name: "파라과이", fullName: "Paraguay", imageName: "Paraguay.png"),
    FlagInfo(name: "페루", fullName: "Peru", imageName: "Peru.png"),
    FlagInfo(name: "폴란드", fullName: "Poland", imageName: "Poland.png"),
    FlagInfo(name: "포르투갈", fullName: "Portugal", imageName: "Portugal.png"),
    FlagInfo(name: "카타르", fullName: "Qatar", imageName: "Qatar.png"),
    FlagInfo(name: "루마니아", fullName: "Romania", imageName: "Romania.png"),
    FlagInfo(name: "러시아 제국", fullName: "Russia", imageName: "Russia.png"),
    FlagInfo(name: "르완다", fullName: "Rwanda", imageName: "Rwanda.png"),
    FlagInfo(name: "세인트 키츠 네비스", fullName: "Saint Kitts and Nevis", imageName: "Saint_Kitts_and_Nevis.png"),
    FlagInfo(name: "세인트 루시아", fullName: "Saint Lucia", imageName: "Saint_Lucia.png"),
    FlagInfo(name: "세인트 빈센트 그레나딘", fullName: "Saint Vincent and the Grenadines", imageName: "Saint_Vincent_and_the_Grenadines.png"),
    FlagInfo(name: "사모아", fullName: "Samoa", imageName: "Samoa.png"),
    FlagInfo(name: "산 마리노", fullName: "San Marino", imageName: "San_Marino.png"),
    FlagInfo(name: "상투 메 프린시 페", fullName: "Sao Tome and Principe", imageName: "Sao_Tome_and_Principe.png"),
    FlagInfo(name: "사우디 아라비아", fullName: "Saudi Arabia", imageName: "Saudi_Arabia.png"),
    FlagInfo(name: "세네갈", fullName: "Senegal", imageName: "Senegal.png"),
    FlagInfo(name: "세르비아", fullName: "Serbia", imageName: "Serbia.png"),
    FlagInfo(name: "세이셸", fullName: "Seychelles", imageName: "Seychelles.png"),
    FlagInfo(name: "시에라 리온", fullName: "Sierra Leone", imageName: "Sierra_Leone.png"),
    FlagInfo(name: "싱가포르", fullName: "Singapore", imageName: "Singapore.png"),
    FlagInfo(name: "슬로바키아", fullName: "Slovakia", imageName: "Slovakia.png"),
    FlagInfo(name: "슬로베니아", fullName: "Slovenia", imageName: "Slovenia.png"),
    FlagInfo(name: "소말리아", fullName: "Somalia", imageName: "Somalia.png"),
    FlagInfo(name: "남아프리카", fullName: "South Africa", imageName: "South_Africa.png"),
    FlagInfo(name: "대한민국", fullName: "South Korea", imageName: "South_Korea.png"),
    FlagInfo(name: "스페인", fullName: "Spain", imageName: "Spain.png"),
    FlagInfo(name: "스리랑카", fullName: "Sri Lanka", imageName: "Sri_Lanka.png"),
    FlagInfo(name: "수리남", fullName: "Suriname", imageName: "Suriname.png"),
    FlagInfo(name: "스와질란드", fullName: "Swaziland", imageName: "Swaziland.png"),
    FlagInfo(name: "스웨덴", fullName: "Sweden", imageName: "Sweden.png"),
    FlagInfo(name: "스위스", fullName: "Switzerland", imageName: "Switzerland.png"),
    FlagInfo(name: "시리아", fullName: "Syria", imageName: "Syria.png"),
    FlagInfo(name: "타지키스탄", fullName: "Tajikistan", imageName: "Tajikistan.png"),
    FlagInfo(name: "탄자니아", fullName: "Tanzania", imageName: "Tanzania.png"),
    FlagInfo(name: "태국", fullName: "Thailand", imageName: "Thailand.png"),
    FlagInfo(name: "감비아", fullName: "The Gambia", imageName: "The_Gambia.png"),
    FlagInfo(name: "가다", fullName: "Togo", imageName: "Togo.png"),
    FlagInfo(name: "통가", fullName: "Tonga", imageName: "Tonga.png"),
    FlagInfo(name: "트리니다드 토바고", fullName: "Trinidad and Tobago", imageName: "Trinidad_and_Tobago.png"),
    FlagInfo(name: "튀니지", fullName: "Tunisia", imageName: "Tunisia.png"),
    FlagInfo(name: "터키", fullName: "Turkey", imageName: "Turkey.png"),
    FlagInfo(name: "투르크 메니스탄", fullName: "Turkmenistan", imageName: "Turkmenistan.png"),
    FlagInfo(name: "투발루", fullName: "Tuvalu", imageName: "Tuvalu.png"),
    FlagInfo(name: "우간다", fullName: "Uganda", imageName: "Uganda.png"),
    FlagInfo(name: "우크라이나", fullName: "Ukraine", imageName: "Ukraine.png"),
    FlagInfo(name: "우루과이", fullName: "Uruguay", imageName: "Uruguay.png"),
    FlagInfo(name: "우즈베키스탄", fullName: "Uzbekistan", imageName: "Uzbekistan.png"),
    FlagInfo(name: "바누아투", fullName: "Vanuatu", imageName: "Vanuatu.png"),
    FlagInfo(name: "베네수엘라", fullName: "Venezuela", imageName: "Venezuela.png"),
    FlagInfo(name: "베트남", fullName: "Vietnam", imageName: "Vietnam.png"),
    FlagInfo(name: "예멘 아랍 공화국", fullName: "Yemen", imageName: "Yemen.png"),
    FlagInfo(name: "잠비아", fullName: "Zambia", imageName: "Zambia.png"),
    FlagInfo(name: "짐바브웨", fullName: "Zimbabwe", imageName: "Zimbabwe.png"),
    FlagInfo(name: "바하마 제도", fullName: "the Bahamas", imageName: "the_Bahamas.png"),
    FlagInfo(name: "중앙 아프리카 공화국", fullName: "the Central African Republic", imageName: "the_Central_African_Republic.png"),
    FlagInfo(name: "코모로", fullName: "the Comoros", imageName: "the_Comoros.png"),
    FlagInfo(name: "체코 공화국", fullName: "the Czech Republic", imageName: "the_Czech_Republic.png"),
    FlagInfo(name: "콩고 민주 공화국", fullName: "the Democratic Republic of the Congo", imageName: "the_Democratic_Republic_of_the_Congo.png"),
    FlagInfo(name: "도미니카 공화국", fullName: "the Dominican Republic", imageName: "the_Dominican_Republic.png"),
    FlagInfo(name: "미크로네시아 연방", fullName: "the Federated States of Micronesia", imageName: "the_Federated_States_of_Micronesia.png"),
    FlagInfo(name: "마샬 군도", fullName: "the Marshall Islands", imageName: "the_Marshall_Islands.png"),
    FlagInfo(name: "네덜란드", fullName: "the Netherlands", imageName: "the_Netherlands.png"),
    FlagInfo(name: "중화 인민 공화국", fullName: "the People's Republic of China", imageName: "the_People's_Republic_of_China.png"),
    FlagInfo(name: "필리핀", fullName: "the Philippines", imageName: "the_Philippines.png"),
    FlagInfo(name: "중화 민국", fullName: "the Republic of China", imageName: "the_Republic_of_China.png"),
    FlagInfo(name: "콩고 공화국", fullName: "the Republic of the Congo", imageName: "the_Republic_of_the_Congo.png"),
    FlagInfo(name: "솔로몬 군도", fullName: "the Solomon Islands", imageName: "the_Solomon_Islands.png"),
    FlagInfo(name: "영국", fullName: "the United Kingdom", imageName: "the_United_Kingdom.png"),
    FlagInfo(name: "미국", fullName: "the United States", imageName: "the_United_States.png"),
    FlagInfo(name: "바티칸 시국", fullName: "the Vatican City", imageName: "the_Vatican_City.png")
]

let countryList = [
    "Afghanistan.png",
    "Albania.png",
    "Algeria.png",
    "Andorra.png",
    "Angola.png",
    "Antigua_and_Barbuda.png",
    "Argentina.png",
    "Armenia.png",
    "Australia.png",
    "Austria.png",
    "Azerbaijan.png",
    "Bahrain.png",
    "Bangladesh.png",
    "Barbados.png",
    "Belarus.png",
    "Belgium.png",
    "Belize.png",
    "Benin.png",
    "Bhutan.png",
    "Bolivia.png",
    "Bosnia_and_Herzegovina.png",
    "Botswana.png",
    "Brazil.png",
    "Brunei.png",
    "Bulgaria.png",
    "Burkina_Faso.png",
    "Cambodia.png",
    "Cameroon.png",
    "Canada.png",
    "Cape_Verde.png",
    "Chile.png",
    "Colombia.png",
    "Costa_Rica.png",
    "Croatia.png",
    "Cuba.png",
    "Cyprus.png",
    "Denmark.png",
    "Djibouti.png",
    "Dominica.png",
    "East_Timor.png",
    "Ecuador.png",
    "Egypt.png",
    "El_Salvador.png",
    "Eritrea.png",
    "Estonia.png",
    "Ethiopia.png",
    "Fiji.png",
    "Finland.png",
    "Burundi.png",
    "Chad.png",
    "Côte_d'Ivoire.png",
    "Equatorial_Guinea.png",
    "Mauritius.png",
    "Mozambique.png",
    "South_Sudan.png",
    "Sudan.png",
    "the_United_Arab_Emirates.png",
    "France.png",
    "Gabon.png",
    "Georgia.png",
    "Germany.png",
    "Ghana.png",
    "Greece.png",
    "Grenada.png",
    "Guatemala.png",
    "Guinea-Bissau.png",
    "Guinea.png",
    "Guyana.png",
    "Haiti.png",
    "Honduras.png",
    "Hungary.png",
    "Iceland.png",
    "India.png",
    "Indonesia.png",
    "Iran.png",
    "Iraq.png",
    "Ireland.png",
    "Israel.png",
    "Italy.png",
    "Jamaica.png",
    "Japan.png",
    "Jordan.png",
    "Kazakhstan.png",
    "Kenya.png",
    "Kiribati.png",
    "Kosovo.png",
    "Kuwait.png",
    "Kyrgyzstan.png",
    "Laos.png",
    "Latvia.png",
    "Lebanon.png",
    "Lesotho.png",
    "Liberia.png",
    "Libya.png",
    "Liechtenstein.png",
    "Lithuania.png",
    "Luxembourg.png",
    "Macedonia.png",
    "Madagascar.png",
    "Malawi.png",
    "Malaysia.png",
    "Maldives.png",
    "Mali.png",
    "Malta.png",
    "Mauritania.png",
    "Mexico.png",
    "Moldova.png",
    "Monaco.png",
    "Mongolia.png",
    "Montenegro.png",
    "Morocco.png",
    "Myanmar.png",
    "Namibia.png",
    "Nauru.png",
    "New_Zealand.png",
    "Nicaragua.png",
    "Niger.png",
    "Nigeria.png",
    "North_Korea.png",
    "Norway.png",
    "Oman.png",
    "Pakistan.png",
    "Palau.png",
    "Palestine.png",
    "Panama.png",
    "Papua_New_Guinea.png",
    "Paraguay.png",
    "Peru.png",
    "Poland.png",
    "Portugal.png",
    "Qatar.png",
    "Romania.png",
    "Russia.png",
    "Rwanda.png",
    "Saint_Kitts_and_Nevis.png",
    "Saint_Lucia.png",
    "Saint_Vincent_and_the_Grenadines.png",
    "Samoa.png",
    "San_Marino.png",
    "Sao_Tome_and_Principe.png",
    "Saudi_Arabia.png",
    "Senegal.png",
    "Serbia.png",
    "Seychelles.png",
    "Sierra_Leone.png",
    "Singapore.png",
    "Slovakia.png",
    "Slovenia.png",
    "Somalia.png",
    "South_Africa.png",
    "South_Korea.png",
    "Spain.png",
    "Sri_Lanka.png",
    "Suriname.png",
    "Swaziland.png",
    "Sweden.png",
    "Switzerland.png",
    "Syria.png",
    "Tajikistan.png",
    "Tanzania.png",
    "Thailand.png",
    "The_Gambia.png",
    "Togo.png",
    "Tonga.png",
    "Trinidad_and_Tobago.png",
    "Tunisia.png",
    "Turkey.png",
    "Turkmenistan.png",
    "Tuvalu.png",
    "Uganda.png",
    "Ukraine.png",
    "Uruguay.png",
    "Uzbekistan.png",
    "Vanuatu.png",
    "Venezuela.png",
    "Vietnam.png",
    "Yemen.png",
    "Zambia.png",
    "Zimbabwe.png",
    "the_Bahamas.png",
    "the_Central_African_Republic.png",
    "the_Comoros.png",
    "the_Czech_Republic.png",
    "the_Democratic_Republic_of_the_Congo.png",
    "the_Dominican_Republic.png",
    "the_Federated_States_of_Micronesia.png",
    "the_Marshall_Islands.png",
    "the_Netherlands.png",
    "the_People's_Republic_of_China.png",
    "the_Philippines.png",
    "the_Republic_of_China.png",
    "the_Republic_of_the_Congo.png",
    "the_Solomon_Islands.png",
    "the_United_Kingdom.png",
    "the_United_States.png",
    "the_Vatican_City.png"
]
